### ISSUE TITLE
Slit displays the dark-gray color as black

### ISSUE THREAD

**Issue by idanarye** [tigrawap/slit#38]
`\e[1;30m` is the color code for showing light gray:
![image](https://user-images.githubusercontent.com/1149255/29023638-3e8d3ca8-7b77-11e7-9b16-457188a10c85.png)

`less` can display it propely
```bash
echo -e "FOO \e[1;30m BAR \e[0m BAZ" | less -R
```
![image](https://user-images.githubusercontent.com/1149255/29023675-68f42d58-7b77-11e7-9a40-e865d2c64665.png)

But `slit` displays it the same as the black background:
```bash
echo -e "FOO \e[1;30m BAR \e[0m BAZ" | slit
```
![image](https://user-images.githubusercontent.com/1149255/29023688-7c9069a8-7b77-11e7-9cf0-d5f440321135.png)

**Comment by tigrawap** [comment]
It actually works for me... what os/term? I'll try in vm on default settings

**Comment by idanarye** [comment]
I'm using [Konsole](https://konsole.kde.org/) on [Arch Linux](https://www.archlinux.org/). And it works when I change the color scheme - but the fact that it shows different result than `less` means there is a problem(it produces a different terminal code?).

BTW - it works fine without PTY: ![image](https://user-images.githubusercontent.com/1149255/30801376-bcd1028a-a1eb-11e7-9e2a-2a06b92d66d2.png)

**Comment by bcicen** [comment]
This is because `1;30m` is the parameter code for **bold** black text.

`cat`, `less` and many other programs will interpret bold+normal color as the high-intensity/light color as well as bold, though much of the time bold text is either not available or is not enabled in the terminal emulator.

opened https://github.com/tigrawap/slit/pull/50 to resolve this difference
