### ISSUE TITLE
add a hotkey for clearing all highlights

### ISSUE THREAD

**Issue by koreno** [tigrawap/slit#80]
this could also be added to the existing `=` key

**Comment by tigrawap** [comment]
I'd rather not have it to use same key, as it's convenient to drop filters and do more searches, while keeping what's already highlighted... And now while we at it - current `=` will actually drop highlight via filters, but won't drop highlights of separate lines. 
Which is not good

So will need a different shortcut to drop highlights of both types

**Comment by koreno** [comment]
btw - `~` - this is a modified _search_, not really a filter. I think it makes more sense to see it as a _search_ that automatically highlights what it finds, since by itself it does not impact the filtering. I think it's more intuitive to think of it that way, and the `=` wouldn't be expected to change anything about highlights.

**Comment by tigrawap** [comment]
It is actually a filter, at least the way it's used here
I.e filter is something, that affects what lines will be displayed and what dropped.
So with ~ lines always displayed, while with `+` they can be dropped by following `-`

In any case, I think we agree on the expected behavior of `=`. I.e not dropping highlights
But then, need to come up with shortcut to drop all highlights :) 

Maybe "ctrl+h". As n + shiftN will be used to navigate highlights.
